"""
Reviewer Agent (Agent 2) — Reviews code generated by Writer Agent against a strict checklist.
Temperature: 0.0, outputs structured pass/fail with issues list.
Max 2 retries on feedback loop.
"""

import json
import logging
from typing import Any

from ..llm import llm_client
from ..config import MAX_REVIEWER_RETRIES

logger = logging.getLogger("ai-agent.reviewer-agent")

SYSTEM_PROMPT = """You are a strict code reviewer for the CMSD (Core Manufacturing Simulation Data) digital twin system.

Your job: Compare generated code against the original code and validate it against this checklist:

1. IMPORTS: Are all necessary modules imported? No missing imports?
2. FIELD TYPES: Are all field types compatible with CMSD Pydantic schema?
3. ERROR HANDLING: Is there proper error handling (try/except, httpx status checks)?
4. SCOPE: Does the diff ONLY touch the intended methods? No unrelated changes?
5. SECRETS: Are there any hardcoded credentials or secrets? These must be flagged as CRITICAL.
6. CODE STYLE: Does the code follow the same async/await pattern as existing methods?
7. PRESERVATION: Are ALL existing methods and imports preserved exactly? Nothing deleted?
8. TYPE HINTS: Do all new methods have proper type hints?
9. HELPER FUNCTIONS: Does the new code use the same helper functions (_to_decimal, _to_duration, etc.) consistently?
10. SYNTAX: Are there obvious syntax errors (missing colons, unbalanced brackets, bad indentation)?

OUTPUT FORMAT — valid JSON only:
{
  "pass": true/false,
  "issues": [
    {
      "severity": "critical|high|medium|low",
      "file": "api_client.py|factory.py",
      "line": "approximate line number or 'N/A'",
      "message": "Clear description of the issue",
      "suggestion": "How to fix it"
    }
  ],
  "recommendation": "APPROVE|APPROVE_WITH_MINOR_FIXES|REJECT",
  "summary": "Brief review summary"
}

RULES:
- 'pass': false if ANY critical or high-severity issues exist
- If REJECTED, provide specific, actionable suggestions for the Writer
- Be thorough but fair — don't flag stylistic preferences as critical

IMPORTANT: Output ONLY the JSON object. No markdown, no explanation text outside the JSON."""


class ReviewerAgent:
    """Agent 2: Reviews generated code against a strict checklist."""

    async def review(
        self,
        original_files: dict[str, str],
        generated_files: dict[str, str],
        confirmed_mapping: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """
        Review generated code against original and mapping.
        Returns structured review with pass/fail and issues.
        """
        user_prompt = self._build_user_prompt(original_files, generated_files, confirmed_mapping)

        for attempt in range(1, MAX_REVIEWER_RETRIES + 1):
            try:
                logger.info(f"Reviewer agent attempt {attempt}/{MAX_REVIEWER_RETRIES}")
                result = llm_client.chat_json(
                    system_prompt=SYSTEM_PROMPT,
                    user_prompt=user_prompt,
                    temperature=0.0,
                )
                validated = self._validate_review(result)
                validated["attempt"] = attempt
                return validated
            except Exception as e:
                logger.warning(f"Reviewer agent attempt {attempt} failed: {e}")
                if attempt == MAX_REVIEWER_RETRIES:
                    return {
                        "pass": False,
                        "issues": [{
                            "severity": "critical",
                            "file": "N/A",
                            "line": "N/A",
                            "message": f"Reviewer agent failed: {e}",
                            "suggestion": "Manual review required"
                        }],
                        "recommendation": "REJECT",
                        "summary": f"Reviewer failed after {MAX_REVIEWER_RETRIES} attempts",
                        "attempt": attempt,
                    }

        return {"pass": False, "issues": [], "recommendation": "REJECT", "attempt": 0}

    def _build_user_prompt(
        self,
        original_files: dict[str, str],
        generated_files: dict[str, str],
        confirmed_mapping: dict[str, Any] | None,
    ) -> str:
        parts = []

        # Show diffs if available, otherwise show both versions
        for path in ["api_client.py", "factory.py"]:
            orig = original_files.get(f"cmsd_twin_service/{path}", "")
            gen = generated_files.get(f"cmsd_twin_service/{path}", "")

            parts.append(f"\n## Original {path}\n```python\n{orig[:3000]}\n```")
            parts.append(f"\n## Generated {path}\n```python\n{gen[:3000]}\n```")

        if confirmed_mapping:
            parts.append(f"\n## Confirmed Mapping\n{json.dumps(confirmed_mapping, indent=2)[:1000]}")

        parts.append("\nReview the generated code against the checklist above.")
        return "\n".join(parts)

    @staticmethod
    def _validate_review(result: dict[str, Any]) -> dict[str, Any]:
        """Validate and normalize the reviewer output."""
        if "pass" not in result:
            raise ValueError("Review output missing 'pass' key")

        issues = result.get("issues", [])
        if not isinstance(issues, list):
            result["issues"] = []

        # Determine recommendation if missing
        if "recommendation" not in result:
            has_critical = any(
                i.get("severity") in ("critical", "high") for i in issues
            )
            result["recommendation"] = "REJECT" if has_critical else "APPROVE"

        result["pass"] = result["recommendation"] != "REJECT"

        return result


# Singleton
reviewer_agent = ReviewerAgent()


